#a= input("birinci sayi:")
#b= input("ikinci sayi:")
#c= input("ucuncu sayi:")
#print('sayilari topla:',int(a)+int(b)+int(c))
print('oyuncu kaydetme programi')
ad = input ('oyuncunun adi:')
soyad= input('oyuncunun soyadi:')
takim=input('oyuncunun takimi:')
bilgiler=[ad,soyad,takim]
print("Database'e kaydediliyor...")
print("Oyuncunun adi:{} \nOyuncunun soyadi:{} \nOyuncunun takimi:{}".format(bilgiler[0],bilgiler[1],bilgiler[2]))
print("kaydedildi...")